--Admin
--drop USER QLKHACHSAN CASCADE;
--Tạo user QLKhachSan như ADMIN để quản lý hệ thống khách sạn
ALTER SESSION SET "_ORACLE_SCRIPT"=TRUE;
CREATE USER QLKhachSan IDENTIFIED BY a;
GRANT CREATE SESSION TO QLKhachSan WITH ADMIN OPTION;
GRANT CONNECT TO QLKhachSan WITH ADMIN OPTION;
GRANT CREATE ROLE TO QLKhachSan WITH ADMIN OPTION;
GRANT ALTER USER TO QLKhachSan WITH ADMIN OPTION;
GRANT CREATE USER TO QLKhachSan WITH ADMIN OPTION;
GRANT ALTER ANY ROLE TO QLKhachSan WITH ADMIN OPTION;
GRANT DROP USER TO QLKhachSan WITH ADMIN OPTION;
GRANT DROP ANY ROLE TO QLKhachSan WITH ADMIN OPTION;
GRANT SELECT ANY DICTIONARY TO QLKhachSan;
GRANT CREATE TABLE TO QLKhachSan;
ALTER SESSION SET "_ORACLE_SCRIPT"=FALSE;
GRANT INSERT ANY TABLE TO QLKhachSan;
GRANT DELETE ANY TABLE TO QLKhachSan;
GRANT UPDATE ANY TABLE TO QLKhachSan;
GRANT CREATE TRIGGER TO QLKhachSan;
GRANT UNLIMITED TABLESPACE TO QLKhachSan;
CONNECT QLKhachSan/a;